name: Fuzz apworld
on:
  push:
  pull_request:

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest AP Version
        id: get_latest_ap_version
        run: |
          echo "AP_VERSION=`wget https://github.com/ArchipelagoMW/Archipelago/releases/latest 2>&1 | grep Location: | awk '{print $2}' | rev | cut -d "/" -f 1 | rev`" >> "$GITHUB_ENV"
      - uses: Eijebong/ap-actions/fuzz@main
        with:
          apworld-path: src
          ap-version: ${{ env.AP_VERSION }}
          python-version: '3.12'
          runs: 500 # This is optional
          yamls-per-run: 1 # This is optional